### ISSUE TITLE
微信问题

### ISSUE THREAD

**Issue by jerryliang122** [wloot/android_kernel_xiaomi_msm8998#2]
在最新的内核刷入最新稳定版（官方的）10.2.1.0 微信会出现录音失败（只出现在语音通话视频通话）听对方的声音会出现卡顿

**Comment by wloot** [comment]
不支持稳定版， 稳定版太旧了。 你可以等下一次稳定版更新，或者刷开发版、体验版

**Comment by wloot** [comment]
最新miui稳定版v10.3声音已正常
